### ISSUE TITLE
Document in docs exactly what the BAM files should contain 

### ISSUE THREAD

**Issue by jfy133** [metaDMG-dev/metaDMG-core#12]
I saw a presentation from Mikkel Pedersen today that included references to metaDMG.

I was reading through the [documentation](https://metadmg-dev.github.io/metaDMG-core/index.html#), and something I noticed was while the inputs are described as 'bam' files, what the BAMs should contain is not described, i.e., 'meta' in the name/use of LCA implies trying to make comparison between references?  Should it be:

- one BAM file including mappings to multiple references, (and you can supply multiple samples in a run) or 
- should a `metaDMG` run only include one sample, with each BAM file representing the mapping of each reference for  that sample (I hope that's clear...! I can rephrase if necessary)

**Comment by miwipe** [comment]
Hi James, 

Thanks for raising this issue, I will update the documentation. 
1. Multiple bam files can be supplied to metaDMG however they should be supplied per sample, or whatever the lowest level you need. 
2. when building the config file using "metaDMG config"  you can supply a wildcard to include multiple files. Like: metaDMG config *.merged.sort.bam
3. metaDMG expects readID, reference id,sequence ,cigar, mdz, and the position. 
4. Remember to sort the bam/sam files by readID.
