### ISSUE TITLE
KeyError when using --forward-only

### ISSUE THREAD

**Issue by genomewalker** [metaDMG-dev/metaDMG-core#3]
Hi @ChristianMichelsen 

the dashboard fails [here](https://github.com/metaDMG-dev/metaDMG-core/blob/main/src/metaDMG/viz/results.py#L108) when visualizing results where the `--forward-only` has been used:

```
raise KeyError(key) from err
KeyError: 'N_x=1_reverse'
```

**Comment by ChristianMichelsen** [comment]
Fixed in v0.24.4
