### ISSUE TITLE
Error when executing in local/global mode

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [metaDMG-dev/metaDMG-core#6]
I get the following error:

`metaDMG.fit.workflow:48 | ERROR | 1 error(s) occurred during the computation.`

Any idea where to start debugging?

Best,
Alex

**Comment by ChristianMichelsen** [comment]
Hi @AlexanderBartholomaeus !

Yeah, I would suggest looking into the log-file. If you can post that, I can take a look.

**Comment by ChristianMichelsen** [comment]
Hm, would it be possible to upload the bam-file? 
I don't see any obvious errors.

**Comment by AlexanderBartholomaeus** [comment]
I sent you a message via mail.

**Comment by ChristianMichelsen** [comment]
It seems to be due to your bam-file not being sorted. Sort it and try again. 
I have updated the error message in v0.32.2 for this bug. 
Please feel free to open this issue again if this does not solve it.

**Comment by AlexanderBartholomaeus** [comment]
The bam files are sorted already. Also another sorting via samtools sort produces identical files.

Did you run successfully on the files I provided? How did you solve it?

**Comment by ChristianMichelsen** [comment]
I sorted the bam-files (by read name as mentioned in the error message) and then it worked.
I even added the command to get it working to the error message.

Mvh,
Christian Michelsen
