### ISSUE TITLE
Error with data frames when computing the bayesian model on large BAM files

### ISSUE THREAD

**Issue by vincentvendius** [metaDMG-dev/metaDMG-core#7]
#Using metaDMG CLI, version: 0.24.4 and running
metaDMG config --overwrite --config-file 2e29899192-config.weight-1.yaml --custom-database --weight-type 1 --names /willerslev/edna/antonio/geogenetics/DBs/gtdb/r202/flavours/hires-organelles-virus/pkg
/taxonomy/names.dmp --nodes /willerslev/edna/antonio/geogenetics/DBs/gtdb/r202/flavours/hires-organelles-virus/pkg/taxonomy/nodes.dmp --acc2tax /willerslev/edna/antonio/geogenetics/DBs/gtdb/r202/flavours
/hires-organelles-virus/pkg/taxonomy/acc2taxid.map.gz --metaDMG-cpp /science/willerslev/users-shared/science-snm-willerslev-xvh856/pipelines/aMAW-taxonomy/packages/metaDMG-cpp/metaDMG-cpp --parallel-samp
les 1 --cores-per-sample 4 --output-dir 2e29899192.tp-mdmg.lca.weight-1 --max-position 35 --lca-rank '' --bayesian --min-similarity-score 0.9 --damage-mode lca /science/willerslev/users-shared/science-sn
m-willerslev-xvh856/pipelines/aMAW-taxonomy/results/taxonomic-profiling/2e29899192.dedup.filtered.bam
#and then on the resulting yaml file
metaDMG compute 2e29899192-config.weight-1.yaml
#gives me python error
AssertionError: Dataframe contains too large values.
#during the computation with the bayesian model:
[2022-09-10 19:11:17] | INFO | 2e29899192 | Fitting the data with a Bayesian model, please wait.

#the error seems to be connected with the size of the bam file. I am receiving this error only on bam files of size >=15G

**Comment by ChristianMichelsen** [comment]
Try to update to v0.31.1 and see if it helps. I have just released it a minute ago, so it might take 5 minutes until you are able to find it. 

Also, please format the output next time, as it makes it a lot easier to interpret the text.
